name: CI Spring Boot

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: maven

      - name: Install dependencies
        run: mvn package -DskipTests

#      - name: Build with Maven
#        run: mvn --batch-mode --update-snapshots verify
#
#      - name: Run Formatter
#        run: mvn com.coveo:fmt-maven-plugin:format

      - name: Test
        run: mvn test

      - name: 'Afficher les stats de Tests et Couverture'
        if: always()
        shell: bash
        run: |
          echo "### 📊 Résumé de la construction" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          # --- 1. CALCUL DES TESTS SUITE ---
          tests=0; failures=0; errors=0; skipped=0
          
          # Extraction des données via xmllint
          for report in target/surefire-reports/TEST-*.xml; do
            if [ -f "$report" ]; then
              t=$(xmllint --xpath "string(/testsuite/@tests)" "$report" 2>/dev/null || echo 0)
              f=$(xmllint --xpath "string(/testsuite/@failures)" "$report" 2>/dev/null || echo 0)
              e=$(xmllint --xpath "string(/testsuite/@errors)" "$report" 2>/dev/null || echo 0)
              s=$(xmllint --xpath "string(/testsuite/@skipped)" "$report" 2>/dev/null || echo 0)
          
              tests=$((tests + ${t:-0}))
              failures=$((failures + ${f:-0}))
              errors=$((errors + ${e:-0}))
              skipped=$((skipped + ${s:-0}))
            fi
          done
          
          executed=$((tests - skipped))
          passed=$((executed - failures - errors))
          
          if [ $executed -gt 0 ]; then
            # Calcul du taux avec awk pour avoir les décimales
            rate=$(awk "BEGIN {printf \"%.2f\", ($passed / $executed) * 100}")
          else
            rate="0.00"
          fi
          
          test_message="✅ **Tests réussis :** $passed/$executed ($rate%)"
          echo "$test_message"
          echo "* $test_message" >> $GITHUB_STEP_SUMMARY